FROM elasticsearch
MAINTAINER HerryHou <HerryHou at gmail dot com>

RUN /usr/share/elasticsearch/bin/plugin -install mobz/elasticsearch-head && \
    /usr/share/elasticsearch/bin/plugin -install lukas-vlcek/bigdesk/2.5.0